# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 12:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 28, 12, 35, 50, 677871, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
